FROM python:3.11

RUN pip install --upgrade pip

RUN groupadd -g 1001 prod && useradd -rms /bin/bash -u 1001 -g 1001 prod && chmod 777 /opt /run

WORKDIR /avito_fast_api

RUN chown -R prod:prod /avito_fast_api && chmod 755 /avito_fast_api

COPY ./avito_fast_api/requirements.txt .

RUN pip install -r requirements.txt

COPY --chown=prod:prod ./avito_fast_api .
