"""added relationship between chat and department

Revision ID: 26ffc9224938
Revises: 1166d80eef72
Create Date: 2024-11-06 13:42:33.040847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ffc9224938'
down_revision: Union[str, None] = '1166d80eef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'department_id')
    # ### end Alembic commands ###
