"""telegram_group_id\

Revision ID: 4002463cbc0a
Revises: 900348885799
Create Date: 2024-10-29 12:42:19.826927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4002463cbc0a'
down_revision: Union[str, None] = '900348885799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('telegram_group_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'telegram_group_id')
    # ### end Alembic commands ###
