"""added department to token

Revision ID: 5bc60cbdbfae
Revises: 26ffc9224938
Create Date: 2025-01-09 12:45:49.242986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc60cbdbfae'
down_revision: Union[str, None] = '26ffc9224938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'token', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'department_id')
    # ### end Alembic commands ###
