"""column created_at in avito_message_model

Revision ID: 76ddf87975a5
Revises: 31483410ac28
Create Date: 2024-10-02 09:29:50.240288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ddf87975a5'
down_revision: Union[str, None] = '31483410ac28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avito_messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('avito_messages', 'read',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avito_messages', 'read',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('avito_messages', 'created_at')
    # ### end Alembic commands ###
