"""chat topic

Revision ID: 8068b1028a80
Revises: 4002463cbc0a
Create Date: 2024-10-29 14:29:44.198509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8068b1028a80'
down_revision: Union[str, None] = '4002463cbc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('telegram_topic', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'telegram_topic')
    # ### end Alembic commands ###
