"""add serialization for call

Revision ID: 8ca08fc24d63
Revises: acc06feb2af2
Create Date: 2024-09-09 16:42:03.259445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca08fc24d63'
down_revision: Union[str, None] = 'acc06feb2af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('tg_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'tg_message_id')
    # ### end Alembic commands ###
