"""add department relation to reviews

Revision ID: f31908ce6661
Revises: 5e3598450955
Create Date: 2025-03-25 17:42:06.525565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31908ce6661'
down_revision: Union[str, None] = '5e3598450955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('department', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'departments', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'department')
    # ### end Alembic commands ###
